name: Deploy Snowpark App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Snowflake CLI
        run: pip install snowflake-cli-labs

      - name: Authenticate Snowflake
        run: |
          snow config init
          snow connection add --connection student_conn --account ${{ secrets.SNOW_ACCOUNT }} --user ${{ secrets.SNOW_USER }} --password ${{ secrets.SNOW_PASSWORD }} --role ACCOUNTADMIN --database snowpark_app --schema snowparkapp_schema --warehouse COMPUTE_WH
          snow connection use student_conn

      - name: Deploy Snowpark App
        run: python deploy_snowpark_app.py $GITHUB_WORKSPACE


# name: Deploy Snowpark Apps

# # Controls when the action will run. 
# on:
#   push:
#     branches:
#       - main

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Setup Python 3.10
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Install Python packages
#         run: pip install -r requirements.txt

#       - name: Deploy Snowpark apps
#         env:
#           SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
#           SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
#           SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
#           SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
#           SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
#           SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
#         run: python deploy_snowpark_app.py $GITHUB_WORKSPACE