name: Deploy Snowpark App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Snowflake CLI
        run: |
          pip install --upgrade snowflake-cli-labs

      - name: Set up Snowflake CLI
        run: |
          pip install snowflake-cli-labs
          snow connection add user_connection \
            --account ${{ secrets.SNOWFLAKE_ACCOUNT }} \
            --username ${{ secrets.SNOWFLAKE_USERNAME }} \
            --password ${{ secrets.SNOWFLAKE_PASSWORD }}

      - name: Run Snowpark App
        run: python deploy_snowpark_app.py
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ACCOUNTADMIN
          SNOWFLAKE_WAREHOUSE: COMPUTE_WH
          SNOWFLAKE_DATABASE: snowpark_app
          SNOWFLAKE_SCHEMA: snowparkapp_schema



# name: Deploy Snowpark Apps

# # Controls when the action will run. 
# on:
#   push:
#     branches:
#       - main

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Setup Python 3.10
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Install Python packages
#         run: pip install -r requirements.txt

#       - name: Deploy Snowpark apps
#         env:
#           SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
#           SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
#           SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
#           SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
#           SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
#           SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
#         run: python deploy_snowpark_app.py $GITHUB_WORKSPACE